import { Notification } from '@/types/notification'

export const mockNotifications: Notification[] = [
  {
    id: '1',
    source: 'coupa-cso',
    priority: 'critical',
    status: 'unread',
    title: 'Urgent: Contract expiring in 48 hours',
    message: 'Strategic supplier contract #SC-2024-089 with Acme Corp expires on Feb 5, 2026. Immediate action required to prevent service disruption.',
    createdAt: new Date('2026-02-03T09:30:00'),
    actionUrl: '/contracts/SC-2024-089',
    metadata: {
      category: 'contract-expiry',
      relatedEntity: 'Acme Corp',
      deadline: new Date('2026-02-05T23:59:59'),
    },
  },
  {
    id: '2',
    source: 'playbook',
    priority: 'high',
    status: 'unread',
    title: 'Price increase notification received',
    message: 'Supplier GlobalTech has submitted a 12% price increase request for Category: Electronics. Review and approval needed.',
    createdAt: new Date('2026-02-03T08:15:00'),
    actionUrl: '/playbook/price-changes/PT-445',
    metadata: {
      category: 'price-change',
      relatedEntity: 'GlobalTech',
    },
  },
  {
    id: '3',
    source: 'onesource',
    priority: 'high',
    status: 'unread',
    title: 'New RFQ responses available',
    message: '8 suppliers have submitted proposals for RFQ-2026-023 (Office Supplies - Q1). Total value: $450K. Review deadline: Feb 6.',
    createdAt: new Date('2026-02-03T07:45:00'),
    actionUrl: '/rfq/RFQ-2026-023',
    metadata: {
      category: 'rfq-response',
      deadline: new Date('2026-02-06T17:00:00'),
    },
  },
  {
    id: '4',
    source: 'business-partner-portal',
    priority: 'critical',
    title: 'Supplier compliance alert',
    message: 'Critical: Supplier TechSolutions Ltd failed quality audit. Non-compliance in 3 categories. Immediate corrective action plan required.',
    status: 'unread',
    createdAt: new Date('2026-02-02T16:20:00'),
    actionUrl: '/compliance/audit/AUD-2026-012',
    metadata: {
      category: 'compliance',
      relatedEntity: 'TechSolutions Ltd',
    },
  },
  {
    id: '5',
    source: 'playbook',
    priority: 'medium',
    status: 'read',
    title: 'Quarterly savings report ready',
    message: 'Q1 2026 savings report is now available. Total savings: $2.3M (18% above target). Review performance metrics.',
    createdAt: new Date('2026-02-02T14:00:00'),
    actionUrl: '/reports/savings/Q1-2026',
    metadata: {
      category: 'report',
    },
  },
  {
    id: '6',
    source: 'coupa-cso',
    priority: 'medium',
    status: 'unread',
    title: 'Purchase requisition pending approval',
    message: 'PR-2026-1234 for IT equipment ($85,000) is awaiting your approval. Requested by: Engineering Dept.',
    createdAt: new Date('2026-02-02T11:30:00'),
    actionUrl: '/approvals/PR-2026-1234',
    metadata: {
      category: 'approval',
    },
  },
  {
    id: '7',
    source: 'onesource',
    priority: 'low',
    status: 'read',
    title: 'Supplier performance score updated',
    message: 'Monthly supplier scorecard updated for 15 active suppliers. Average performance: 87/100 (↑3 points).',
    createdAt: new Date('2026-02-01T09:00:00'),
    actionUrl: '/suppliers/scorecard',
    metadata: {
      category: 'performance',
    },
  },
  {
    id: '8',
    source: 'business-partner-portal',
    priority: 'high',
    status: 'unread',
    title: 'New supplier onboarding required',
    message: 'Business unit has requested onboarding for new supplier: InnovateCo. Estimated annual spend: $500K. Start due diligence process.',
    createdAt: new Date('2026-02-01T08:00:00'),
    actionUrl: '/onboarding/new/INC-2026-003',
    metadata: {
      category: 'onboarding',
      relatedEntity: 'InnovateCo',
    },
  },
  {
    id: '9',
    source: 'playbook',
    priority: 'medium',
    status: 'read',
    title: 'Category strategy review scheduled',
    message: 'Annual category strategy review for IT & Telecom scheduled for Feb 10. Please prepare updated spend analysis.',
    createdAt: new Date('2026-01-31T15:00:00'),
    actionUrl: '/strategy/review/IT-TELECOM-2026',
    metadata: {
      category: 'strategy',
      deadline: new Date('2026-02-10T10:00:00'),
    },
  },
  {
    id: '10',
    source: 'coupa-cso',
    priority: 'low',
    status: 'dismissed',
    title: 'System maintenance scheduled',
    message: 'Coupa CSO will undergo maintenance on Feb 8, 2026 from 02:00-04:00 UTC. Limited functionality during this window.',
    createdAt: new Date('2026-01-30T10:00:00'),
    metadata: {
      category: 'system',
    },
  },
]
